# Generated by Django 5.0.6 on 2024-06-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradress',
            name='is_bankrupt',
            field=models.BooleanField(default=False),
        ),
    ]
