# Generated by Django 5.0.6 on 2024-06-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='accoutn',
            new_name='account',
        ),
    ]
