# Generated by Django 5.0.6 on 2024-06-26 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_recieving_account_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after_transaction',
        ),
    ]
